package com.mazadak.payment.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The response body returned after a refund has been processed.")
public record RefundResponse(

        @Schema(description = "The unique identifier for the refund object, generated by Stripe (e.g., 're_...').",
                example = "re_3P5Y2e1eZvKYlo2C0a1b2c3d")
        String refundId,

        @Schema(description = "The order ID associated with the transaction that was refunded.",
                example = "order-abc-123")
        String orderId,

        @Schema(description = "The status of the refund as reported by Stripe.",
                example = "succeeded")
        String status,

        @Schema(description = "A confirmation or error message providing more details about the refund status.",
                example = "Refund processed successfully.")
        String message
) {}
